name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y llvm-9-dev
        cargo install just
        #echo $PATH
        # install just
        #curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to opt

    - name: Cache Global Stack
      uses: actions/cache@v1
      with:
        path: ~/.stack/
        key: stack-global-${{ hashFiles('package.yaml') }}-${{ hashFiles('stack.yaml') }}
        restore-keys: stack-global

    - name: Install Dependencies
      run: stack --no-terminal --install-ghc test --only-dependencies

    - name: Build
      run: stack build

    - name: Test
      run: stack test
