name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Packages
      run: |
        # get system packages
        sudo apt-get update
        sudo apt-get install -y llvm-9-dev

        # install just
        curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/share/rust/.cargo/bin

    - name: Cache Global Stack
      uses: actions/cache@v1
      with:
        path: ~/.stack/
        key: stack-global-${{ hashFiles('package.yaml') }}-${{ hashFiles('stack.yaml') }}
        restore-keys: stack-global

    - name: Install Dependencies
      run: just install-dev-deps

    - name: Build
      run: just build

    - name: Test
      run: just test
