name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Image
      run: docker build --tag=llvm-lambda-ci --file=Dockerfile .

    - name: Build
      run: docker run --mount "type=bind,src=$(pwd),dst=/root/llvm-lambda" llvm-lambda-ci bash -c 'cd ~/llvm-lambda && stack build && stack test'
