name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y llvm-5.0-dev

    - name: Cache Global Stack
      uses: actions/cache@v1
      with:
        path: ~/.stack/
        key: stack-${{ hashFiles("package.yaml") }}-${{ hashFiles("stack.yaml") }}
        restore-keys: stack

    - name: Cache Local Stack
      uses: actions/cache@v1
      with:
        path: .stack-work/
        key: stack-work

    - name: Install Dependencies
      run: stack --no-terminal --install-ghc test --only-dependencies

    - name: Build
      run: stack build

    - name: Test
      run: stack test
