name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Docker Image
      id: cache
      uses: actions/cache@v1
      with:
        path: docker-cache/
        key: docker-image-cache

    - name: Load Cache
      if: steps.cache.outputs.cache-hit == 'true'
      run: gunzip --stdout docker-cache/image.tar.gz | docker load

    - name: Build Image
      run: |
        docker build --tag=llvm-lambda-ci --file=Dockerfile .
        mkdir -p docker-cache
        docker save llvm-lambda-ci | gzip > docker-cache/image.tar.gz

    - name: Build
      run: docker run --mount "type=bind,src=$(pwd),dst=/root/llvm-lambda" llvm-lambda-ci stack --no-terminal --allow-different-user test --bench --no-run-benchmarks --haddock --no-haddock-deps
